mqtt:
  uri: "tcp://apache-apollo:61613"
  username: "admin"
  password: "password"
  clientId: "SliwServer"
spring:
  data:
    elasticsearch:
      cluster-name: "elasticsearch"
      cluster-nodes: "elasticsearch:9300"
